name: demo
version: 1.0.0
config-version: 2
profile: demo
model-paths:
  - models
test-paths:
  - tests
analysis-paths:
  - analyses
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_packages
models:
  demo:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
