demo_ec:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dwh-db
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: dbt_warehouse
      schema: public
      threads: 4
      sslmode: disable
